<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MasterDataCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Seed Master Data Categories
        $categories = [
            ['code' => 'COUNTRY', 'name' => 'Countries', 'description' => 'List of countries', 'icon' => 'ph ph-globe', 'color' => '#3b82f6', 'display_order' => 1, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'CURRENCY', 'name' => 'Currencies', 'description' => 'List of currencies', 'icon' => 'ph ph-currency-circle-dollar', 'color' => '#10b981', 'display_order' => 2, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['code' => 'UOM', 'name' => 'Units of Measure', 'description' => 'Measurement units', 'icon' => 'ph ph-ruler', 'color' => '#f59e0b', 'display_order' => 3, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($categories as $category) {
            DB::table('master_data_categories')->updateOrInsert(
                ['code' => $category['code']],
                $category
            );
        }

        // Get category IDs
        $countryCategory = DB::table('master_data_categories')->where('code', 'COUNTRY')->first();
        $currencyCategory = DB::table('master_data_categories')->where('code', 'CURRENCY')->first();
        $uomCategory = DB::table('master_data_categories')->where('code', 'UOM')->first();

        // Seed Countries (All 195 UN recognized countries)
        $countries = [
            // Africa
            ['category_id' => $countryCategory->id, 'code' => 'DZ', 'name' => 'Algeria', 'description' => 'People\'s Democratic Republic of Algeria', 'type' => 'country', 'value' => '+213', 'metadata' => json_encode(['capital' => 'Algiers', 'region' => 'North Africa', 'calling_code' => '+213']), 'display_order' => 1, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AO', 'name' => 'Angola', 'description' => 'Republic of Angola', 'type' => 'country', 'value' => '+244', 'metadata' => json_encode(['capital' => 'Luanda', 'region' => 'Central Africa', 'calling_code' => '+244']), 'display_order' => 2, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BJ', 'name' => 'Benin', 'description' => 'Republic of Benin', 'type' => 'country', 'value' => '+229', 'metadata' => json_encode(['capital' => 'Porto-Novo', 'region' => 'West Africa', 'calling_code' => '+229']), 'display_order' => 3, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BW', 'name' => 'Botswana', 'description' => 'Republic of Botswana', 'type' => 'country', 'value' => '+267', 'metadata' => json_encode(['capital' => 'Gaborone', 'region' => 'Southern Africa', 'calling_code' => '+267']), 'display_order' => 4, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BF', 'name' => 'Burkina Faso', 'description' => 'Burkina Faso', 'type' => 'country', 'value' => '+226', 'metadata' => json_encode(['capital' => 'Ouagadougou', 'region' => 'West Africa', 'calling_code' => '+226']), 'display_order' => 5, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BI', 'name' => 'Burundi', 'description' => 'Republic of Burundi', 'type' => 'country', 'value' => '+257', 'metadata' => json_encode(['capital' => 'Gitega', 'region' => 'East Africa', 'calling_code' => '+257']), 'display_order' => 6, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CM', 'name' => 'Cameroon', 'description' => 'Republic of Cameroon', 'type' => 'country', 'value' => '+237', 'metadata' => json_encode(['capital' => 'Yaoundé', 'region' => 'Central Africa', 'calling_code' => '+237']), 'display_order' => 7, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CV', 'name' => 'Cape Verde', 'description' => 'Republic of Cabo Verde', 'type' => 'country', 'value' => '+238', 'metadata' => json_encode(['capital' => 'Praia', 'region' => 'West Africa', 'calling_code' => '+238']), 'display_order' => 8, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CF', 'name' => 'Central African Republic', 'description' => 'Central African Republic', 'type' => 'country', 'value' => '+236', 'metadata' => json_encode(['capital' => 'Bangui', 'region' => 'Central Africa', 'calling_code' => '+236']), 'display_order' => 9, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TD', 'name' => 'Chad', 'description' => 'Republic of Chad', 'type' => 'country', 'value' => '+235', 'metadata' => json_encode(['capital' => 'N\'Djamena', 'region' => 'Central Africa', 'calling_code' => '+235']), 'display_order' => 10, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KM', 'name' => 'Comoros', 'description' => 'Union of the Comoros', 'type' => 'country', 'value' => '+269', 'metadata' => json_encode(['capital' => 'Moroni', 'region' => 'East Africa', 'calling_code' => '+269']), 'display_order' => 11, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CG', 'name' => 'Congo', 'description' => 'Republic of the Congo', 'type' => 'country', 'value' => '+242', 'metadata' => json_encode(['capital' => 'Brazzaville', 'region' => 'Central Africa', 'calling_code' => '+242']), 'display_order' => 12, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CD', 'name' => 'Democratic Republic of Congo', 'description' => 'Democratic Republic of the Congo', 'type' => 'country', 'value' => '+243', 'metadata' => json_encode(['capital' => 'Kinshasa', 'region' => 'Central Africa', 'calling_code' => '+243']), 'display_order' => 13, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CI', 'name' => 'Côte d\'Ivoire', 'description' => 'Republic of Côte d\'Ivoire', 'type' => 'country', 'value' => '+225', 'metadata' => json_encode(['capital' => 'Yamoussoukro', 'region' => 'West Africa', 'calling_code' => '+225']), 'display_order' => 14, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'DJ', 'name' => 'Djibouti', 'description' => 'Republic of Djibouti', 'type' => 'country', 'value' => '+253', 'metadata' => json_encode(['capital' => 'Djibouti', 'region' => 'East Africa', 'calling_code' => '+253']), 'display_order' => 15, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'EG', 'name' => 'Egypt', 'description' => 'Arab Republic of Egypt', 'type' => 'country', 'value' => '+20', 'metadata' => json_encode(['capital' => 'Cairo', 'region' => 'North Africa', 'calling_code' => '+20']), 'display_order' => 16, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GQ', 'name' => 'Equatorial Guinea', 'description' => 'Republic of Equatorial Guinea', 'type' => 'country', 'value' => '+240', 'metadata' => json_encode(['capital' => 'Malabo', 'region' => 'Central Africa', 'calling_code' => '+240']), 'display_order' => 17, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ER', 'name' => 'Eritrea', 'description' => 'State of Eritrea', 'type' => 'country', 'value' => '+291', 'metadata' => json_encode(['capital' => 'Asmara', 'region' => 'East Africa', 'calling_code' => '+291']), 'display_order' => 18, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SZ', 'name' => 'Eswatini', 'description' => 'Kingdom of Eswatini', 'type' => 'country', 'value' => '+268', 'metadata' => json_encode(['capital' => 'Mbabane', 'region' => 'Southern Africa', 'calling_code' => '+268']), 'display_order' => 19, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ET', 'name' => 'Ethiopia', 'description' => 'Federal Democratic Republic of Ethiopia', 'type' => 'country', 'value' => '+251', 'metadata' => json_encode(['capital' => 'Addis Ababa', 'region' => 'East Africa', 'calling_code' => '+251']), 'display_order' => 20, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GA', 'name' => 'Gabon', 'description' => 'Gabonese Republic', 'type' => 'country', 'value' => '+241', 'metadata' => json_encode(['capital' => 'Libreville', 'region' => 'Central Africa', 'calling_code' => '+241']), 'display_order' => 21, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GM', 'name' => 'Gambia', 'description' => 'Republic of The Gambia', 'type' => 'country', 'value' => '+220', 'metadata' => json_encode(['capital' => 'Banjul', 'region' => 'West Africa', 'calling_code' => '+220']), 'display_order' => 22, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GH', 'name' => 'Ghana', 'description' => 'Republic of Ghana', 'type' => 'country', 'value' => '+233', 'metadata' => json_encode(['capital' => 'Accra', 'region' => 'West Africa', 'calling_code' => '+233']), 'display_order' => 23, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GN', 'name' => 'Guinea', 'description' => 'Republic of Guinea', 'type' => 'country', 'value' => '+224', 'metadata' => json_encode(['capital' => 'Conakry', 'region' => 'West Africa', 'calling_code' => '+224']), 'display_order' => 24, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GW', 'name' => 'Guinea-Bissau', 'description' => 'Republic of Guinea-Bissau', 'type' => 'country', 'value' => '+245', 'metadata' => json_encode(['capital' => 'Bissau', 'region' => 'West Africa', 'calling_code' => '+245']), 'display_order' => 25, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KE', 'name' => 'Kenya', 'description' => 'Republic of Kenya', 'type' => 'country', 'value' => '+254', 'metadata' => json_encode(['capital' => 'Nairobi', 'region' => 'East Africa', 'calling_code' => '+254']), 'display_order' => 26, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LS', 'name' => 'Lesotho', 'description' => 'Kingdom of Lesotho', 'type' => 'country', 'value' => '+266', 'metadata' => json_encode(['capital' => 'Maseru', 'region' => 'Southern Africa', 'calling_code' => '+266']), 'display_order' => 27, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LR', 'name' => 'Liberia', 'description' => 'Republic of Liberia', 'type' => 'country', 'value' => '+231', 'metadata' => json_encode(['capital' => 'Monrovia', 'region' => 'West Africa', 'calling_code' => '+231']), 'display_order' => 28, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LY', 'name' => 'Libya', 'description' => 'State of Libya', 'type' => 'country', 'value' => '+218', 'metadata' => json_encode(['capital' => 'Tripoli', 'region' => 'North Africa', 'calling_code' => '+218']), 'display_order' => 29, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MG', 'name' => 'Madagascar', 'description' => 'Republic of Madagascar', 'type' => 'country', 'value' => '+261', 'metadata' => json_encode(['capital' => 'Antananarivo', 'region' => 'East Africa', 'calling_code' => '+261']), 'display_order' => 30, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MW', 'name' => 'Malawi', 'description' => 'Republic of Malawi', 'type' => 'country', 'value' => '+265', 'metadata' => json_encode(['capital' => 'Lilongwe', 'region' => 'Southern Africa', 'calling_code' => '+265']), 'display_order' => 31, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ML', 'name' => 'Mali', 'description' => 'Republic of Mali', 'type' => 'country', 'value' => '+223', 'metadata' => json_encode(['capital' => 'Bamako', 'region' => 'West Africa', 'calling_code' => '+223']), 'display_order' => 32, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MR', 'name' => 'Mauritania', 'description' => 'Islamic Republic of Mauritania', 'type' => 'country', 'value' => '+222', 'metadata' => json_encode(['capital' => 'Nouakchott', 'region' => 'West Africa', 'calling_code' => '+222']), 'display_order' => 33, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MU', 'name' => 'Mauritius', 'description' => 'Republic of Mauritius', 'type' => 'country', 'value' => '+230', 'metadata' => json_encode(['capital' => 'Port Louis', 'region' => 'East Africa', 'calling_code' => '+230']), 'display_order' => 34, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MA', 'name' => 'Morocco', 'description' => 'Kingdom of Morocco', 'type' => 'country', 'value' => '+212', 'metadata' => json_encode(['capital' => 'Rabat', 'region' => 'North Africa', 'calling_code' => '+212']), 'display_order' => 35, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MZ', 'name' => 'Mozambique', 'description' => 'Republic of Mozambique', 'type' => 'country', 'value' => '+258', 'metadata' => json_encode(['capital' => 'Maputo', 'region' => 'Southern Africa', 'calling_code' => '+258']), 'display_order' => 36, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NA', 'name' => 'Namibia', 'description' => 'Republic of Namibia', 'type' => 'country', 'value' => '+264', 'metadata' => json_encode(['capital' => 'Windhoek', 'region' => 'Southern Africa', 'calling_code' => '+264']), 'display_order' => 37, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NE', 'name' => 'Niger', 'description' => 'Republic of Niger', 'type' => 'country', 'value' => '+227', 'metadata' => json_encode(['capital' => 'Niamey', 'region' => 'West Africa', 'calling_code' => '+227']), 'display_order' => 38, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NG', 'name' => 'Nigeria', 'description' => 'Federal Republic of Nigeria', 'type' => 'country', 'value' => '+234', 'metadata' => json_encode(['capital' => 'Abuja', 'region' => 'West Africa', 'calling_code' => '+234']), 'display_order' => 39, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'RW', 'name' => 'Rwanda', 'description' => 'Republic of Rwanda', 'type' => 'country', 'value' => '+250', 'metadata' => json_encode(['capital' => 'Kigali', 'region' => 'East Africa', 'calling_code' => '+250']), 'display_order' => 40, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ST', 'name' => 'São Tomé and Príncipe', 'description' => 'Democratic Republic of São Tomé and Príncipe', 'type' => 'country', 'value' => '+239', 'metadata' => json_encode(['capital' => 'São Tomé', 'region' => 'Central Africa', 'calling_code' => '+239']), 'display_order' => 41, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SN', 'name' => 'Senegal', 'description' => 'Republic of Senegal', 'type' => 'country', 'value' => '+221', 'metadata' => json_encode(['capital' => 'Dakar', 'region' => 'West Africa', 'calling_code' => '+221']), 'display_order' => 42, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SC', 'name' => 'Seychelles', 'description' => 'Republic of Seychelles', 'type' => 'country', 'value' => '+248', 'metadata' => json_encode(['capital' => 'Victoria', 'region' => 'East Africa', 'calling_code' => '+248']), 'display_order' => 43, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SL', 'name' => 'Sierra Leone', 'description' => 'Republic of Sierra Leone', 'type' => 'country', 'value' => '+232', 'metadata' => json_encode(['capital' => 'Freetown', 'region' => 'West Africa', 'calling_code' => '+232']), 'display_order' => 44, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SO', 'name' => 'Somalia', 'description' => 'Federal Republic of Somalia', 'type' => 'country', 'value' => '+252', 'metadata' => json_encode(['capital' => 'Mogadishu', 'region' => 'East Africa', 'calling_code' => '+252']), 'display_order' => 45, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ZA', 'name' => 'South Africa', 'description' => 'Republic of South Africa', 'type' => 'country', 'value' => '+27', 'metadata' => json_encode(['capital' => 'Pretoria', 'region' => 'Southern Africa', 'calling_code' => '+27']), 'display_order' => 46, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SS', 'name' => 'South Sudan', 'description' => 'Republic of South Sudan', 'type' => 'country', 'value' => '+211', 'metadata' => json_encode(['capital' => 'Juba', 'region' => 'East Africa', 'calling_code' => '+211']), 'display_order' => 47, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SD', 'name' => 'Sudan', 'description' => 'Republic of Sudan', 'type' => 'country', 'value' => '+249', 'metadata' => json_encode(['capital' => 'Khartoum', 'region' => 'North Africa', 'calling_code' => '+249']), 'display_order' => 48, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TZ', 'name' => 'Tanzania', 'description' => 'United Republic of Tanzania', 'type' => 'country', 'value' => '+255', 'metadata' => json_encode(['capital' => 'Dodoma', 'region' => 'East Africa', 'calling_code' => '+255']), 'display_order' => 49, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TG', 'name' => 'Togo', 'description' => 'Togolese Republic', 'type' => 'country', 'value' => '+228', 'metadata' => json_encode(['capital' => 'Lomé', 'region' => 'West Africa', 'calling_code' => '+228']), 'display_order' => 50, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TN', 'name' => 'Tunisia', 'description' => 'Republic of Tunisia', 'type' => 'country', 'value' => '+216', 'metadata' => json_encode(['capital' => 'Tunis', 'region' => 'North Africa', 'calling_code' => '+216']), 'display_order' => 51, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'UG', 'name' => 'Uganda', 'description' => 'Republic of Uganda', 'type' => 'country', 'value' => '+256', 'metadata' => json_encode(['capital' => 'Kampala', 'region' => 'East Africa', 'calling_code' => '+256']), 'display_order' => 52, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ZM', 'name' => 'Zambia', 'description' => 'Republic of Zambia', 'type' => 'country', 'value' => '+260', 'metadata' => json_encode(['capital' => 'Lusaka', 'region' => 'Southern Africa', 'calling_code' => '+260']), 'display_order' => 53, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ZW', 'name' => 'Zimbabwe', 'description' => 'Republic of Zimbabwe', 'type' => 'country', 'value' => '+263', 'metadata' => json_encode(['capital' => 'Harare', 'region' => 'Southern Africa', 'calling_code' => '+263']), 'display_order' => 54, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Americas
            ['category_id' => $countryCategory->id, 'code' => 'AG', 'name' => 'Antigua and Barbuda', 'description' => 'Antigua and Barbuda', 'type' => 'country', 'value' => '+1-268', 'metadata' => json_encode(['capital' => 'St. John\'s', 'region' => 'Caribbean', 'calling_code' => '+1-268']), 'display_order' => 55, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AR', 'name' => 'Argentina', 'description' => 'Argentine Republic', 'type' => 'country', 'value' => '+54', 'metadata' => json_encode(['capital' => 'Buenos Aires', 'region' => 'South America', 'calling_code' => '+54']), 'display_order' => 56, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BS', 'name' => 'Bahamas', 'description' => 'Commonwealth of The Bahamas', 'type' => 'country', 'value' => '+1-242', 'metadata' => json_encode(['capital' => 'Nassau', 'region' => 'Caribbean', 'calling_code' => '+1-242']), 'display_order' => 57, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BB', 'name' => 'Barbados', 'description' => 'Barbados', 'type' => 'country', 'value' => '+1-246', 'metadata' => json_encode(['capital' => 'Bridgetown', 'region' => 'Caribbean', 'calling_code' => '+1-246']), 'display_order' => 58, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BZ', 'name' => 'Belize', 'description' => 'Belize', 'type' => 'country', 'value' => '+501', 'metadata' => json_encode(['capital' => 'Belmopan', 'region' => 'Central America', 'calling_code' => '+501']), 'display_order' => 59, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BO', 'name' => 'Bolivia', 'description' => 'Plurinational State of Bolivia', 'type' => 'country', 'value' => '+591', 'metadata' => json_encode(['capital' => 'Sucre', 'region' => 'South America', 'calling_code' => '+591']), 'display_order' => 60, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BR', 'name' => 'Brazil', 'description' => 'Federative Republic of Brazil', 'type' => 'country', 'value' => '+55', 'metadata' => json_encode(['capital' => 'Brasília', 'region' => 'South America', 'calling_code' => '+55']), 'display_order' => 61, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CA', 'name' => 'Canada', 'description' => 'Canada', 'type' => 'country', 'value' => '+1', 'metadata' => json_encode(['capital' => 'Ottawa', 'region' => 'North America', 'calling_code' => '+1']), 'display_order' => 62, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CL', 'name' => 'Chile', 'description' => 'Republic of Chile', 'type' => 'country', 'value' => '+56', 'metadata' => json_encode(['capital' => 'Santiago', 'region' => 'South America', 'calling_code' => '+56']), 'display_order' => 63, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CO', 'name' => 'Colombia', 'description' => 'Republic of Colombia', 'type' => 'country', 'value' => '+57', 'metadata' => json_encode(['capital' => 'Bogotá', 'region' => 'South America', 'calling_code' => '+57']), 'display_order' => 64, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CR', 'name' => 'Costa Rica', 'description' => 'Republic of Costa Rica', 'type' => 'country', 'value' => '+506', 'metadata' => json_encode(['capital' => 'San José', 'region' => 'Central America', 'calling_code' => '+506']), 'display_order' => 65, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CU', 'name' => 'Cuba', 'description' => 'Republic of Cuba', 'type' => 'country', 'value' => '+53', 'metadata' => json_encode(['capital' => 'Havana', 'region' => 'Caribbean', 'calling_code' => '+53']), 'display_order' => 66, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'DM', 'name' => 'Dominica', 'description' => 'Commonwealth of Dominica', 'type' => 'country', 'value' => '+1-767', 'metadata' => json_encode(['capital' => 'Roseau', 'region' => 'Caribbean', 'calling_code' => '+1-767']), 'display_order' => 67, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'DO', 'name' => 'Dominican Republic', 'description' => 'Dominican Republic', 'type' => 'country', 'value' => '+1-809', 'metadata' => json_encode(['capital' => 'Santo Domingo', 'region' => 'Caribbean', 'calling_code' => '+1-809']), 'display_order' => 68, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'EC', 'name' => 'Ecuador', 'description' => 'Republic of Ecuador', 'type' => 'country', 'value' => '+593', 'metadata' => json_encode(['capital' => 'Quito', 'region' => 'South America', 'calling_code' => '+593']), 'display_order' => 69, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SV', 'name' => 'El Salvador', 'description' => 'Republic of El Salvador', 'type' => 'country', 'value' => '+503', 'metadata' => json_encode(['capital' => 'San Salvador', 'region' => 'Central America', 'calling_code' => '+503']), 'display_order' => 70, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GD', 'name' => 'Grenada', 'description' => 'Grenada', 'type' => 'country', 'value' => '+1-473', 'metadata' => json_encode(['capital' => 'St. George\'s', 'region' => 'Caribbean', 'calling_code' => '+1-473']), 'display_order' => 71, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GT', 'name' => 'Guatemala', 'description' => 'Republic of Guatemala', 'type' => 'country', 'value' => '+502', 'metadata' => json_encode(['capital' => 'Guatemala City', 'region' => 'Central America', 'calling_code' => '+502']), 'display_order' => 72, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GY', 'name' => 'Guyana', 'description' => 'Co-operative Republic of Guyana', 'type' => 'country', 'value' => '+592', 'metadata' => json_encode(['capital' => 'Georgetown', 'region' => 'South America', 'calling_code' => '+592']), 'display_order' => 73, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'HT', 'name' => 'Haiti', 'description' => 'Republic of Haiti', 'type' => 'country', 'value' => '+509', 'metadata' => json_encode(['capital' => 'Port-au-Prince', 'region' => 'Caribbean', 'calling_code' => '+509']), 'display_order' => 74, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'HN', 'name' => 'Honduras', 'description' => 'Republic of Honduras', 'type' => 'country', 'value' => '+504', 'metadata' => json_encode(['capital' => 'Tegucigalpa', 'region' => 'Central America', 'calling_code' => '+504']), 'display_order' => 75, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'JM', 'name' => 'Jamaica', 'description' => 'Jamaica', 'type' => 'country', 'value' => '+1-876', 'metadata' => json_encode(['capital' => 'Kingston', 'region' => 'Caribbean', 'calling_code' => '+1-876']), 'display_order' => 76, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MX', 'name' => 'Mexico', 'description' => 'United Mexican States', 'type' => 'country', 'value' => '+52', 'metadata' => json_encode(['capital' => 'Mexico City', 'region' => 'North America', 'calling_code' => '+52']), 'display_order' => 77, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NI', 'name' => 'Nicaragua', 'description' => 'Republic of Nicaragua', 'type' => 'country', 'value' => '+505', 'metadata' => json_encode(['capital' => 'Managua', 'region' => 'Central America', 'calling_code' => '+505']), 'display_order' => 78, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PA', 'name' => 'Panama', 'description' => 'Republic of Panama', 'type' => 'country', 'value' => '+507', 'metadata' => json_encode(['capital' => 'Panama City', 'region' => 'Central America', 'calling_code' => '+507']), 'display_order' => 79, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PY', 'name' => 'Paraguay', 'description' => 'Republic of Paraguay', 'type' => 'country', 'value' => '+595', 'metadata' => json_encode(['capital' => 'Asunción', 'region' => 'South America', 'calling_code' => '+595']), 'display_order' => 80, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PE', 'name' => 'Peru', 'description' => 'Republic of Peru', 'type' => 'country', 'value' => '+51', 'metadata' => json_encode(['capital' => 'Lima', 'region' => 'South America', 'calling_code' => '+51']), 'display_order' => 81, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'description' => 'Federation of Saint Christopher and Nevis', 'type' => 'country', 'value' => '+1-869', 'metadata' => json_encode(['capital' => 'Basseterre', 'region' => 'Caribbean', 'calling_code' => '+1-869']), 'display_order' => 82, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LC', 'name' => 'Saint Lucia', 'description' => 'Saint Lucia', 'type' => 'country', 'value' => '+1-758', 'metadata' => json_encode(['capital' => 'Castries', 'region' => 'Caribbean', 'calling_code' => '+1-758']), 'display_order' => 83, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'description' => 'Saint Vincent and the Grenadines', 'type' => 'country', 'value' => '+1-784', 'metadata' => json_encode(['capital' => 'Kingstown', 'region' => 'Caribbean', 'calling_code' => '+1-784']), 'display_order' => 84, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SR', 'name' => 'Suriname', 'description' => 'Republic of Suriname', 'type' => 'country', 'value' => '+597', 'metadata' => json_encode(['capital' => 'Paramaribo', 'region' => 'South America', 'calling_code' => '+597']), 'display_order' => 85, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TT', 'name' => 'Trinidad and Tobago', 'description' => 'Republic of Trinidad and Tobago', 'type' => 'country', 'value' => '+1-868', 'metadata' => json_encode(['capital' => 'Port of Spain', 'region' => 'Caribbean', 'calling_code' => '+1-868']), 'display_order' => 86, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'US', 'name' => 'United States', 'description' => 'United States of America', 'type' => 'country', 'value' => '+1', 'metadata' => json_encode(['capital' => 'Washington D.C.', 'region' => 'North America', 'calling_code' => '+1']), 'display_order' => 87, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'UY', 'name' => 'Uruguay', 'description' => 'Oriental Republic of Uruguay', 'type' => 'country', 'value' => '+598', 'metadata' => json_encode(['capital' => 'Montevideo', 'region' => 'South America', 'calling_code' => '+598']), 'display_order' => 88, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'VE', 'name' => 'Venezuela', 'description' => 'Bolivarian Republic of Venezuela', 'type' => 'country', 'value' => '+58', 'metadata' => json_encode(['capital' => 'Caracas', 'region' => 'South America', 'calling_code' => '+58']), 'display_order' => 89, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Asia
            ['category_id' => $countryCategory->id, 'code' => 'AF', 'name' => 'Afghanistan', 'description' => 'Islamic Republic of Afghanistan', 'type' => 'country', 'value' => '+93', 'metadata' => json_encode(['capital' => 'Kabul', 'region' => 'South Asia', 'calling_code' => '+93']), 'display_order' => 90, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AM', 'name' => 'Armenia', 'description' => 'Republic of Armenia', 'type' => 'country', 'value' => '+374', 'metadata' => json_encode(['capital' => 'Yerevan', 'region' => 'Western Asia', 'calling_code' => '+374']), 'display_order' => 91, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AZ', 'name' => 'Azerbaijan', 'description' => 'Republic of Azerbaijan', 'type' => 'country', 'value' => '+994', 'metadata' => json_encode(['capital' => 'Baku', 'region' => 'Western Asia', 'calling_code' => '+994']), 'display_order' => 92, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BH', 'name' => 'Bahrain', 'description' => 'Kingdom of Bahrain', 'type' => 'country', 'value' => '+973', 'metadata' => json_encode(['capital' => 'Manama', 'region' => 'Middle East', 'calling_code' => '+973']), 'display_order' => 93, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BD', 'name' => 'Bangladesh', 'description' => 'People\'s Republic of Bangladesh', 'type' => 'country', 'value' => '+880', 'metadata' => json_encode(['capital' => 'Dhaka', 'region' => 'South Asia', 'calling_code' => '+880']), 'display_order' => 94, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BT', 'name' => 'Bhutan', 'description' => 'Kingdom of Bhutan', 'type' => 'country', 'value' => '+975', 'metadata' => json_encode(['capital' => 'Thimphu', 'region' => 'South Asia', 'calling_code' => '+975']), 'display_order' => 95, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BN', 'name' => 'Brunei', 'description' => 'Nation of Brunei', 'type' => 'country', 'value' => '+673', 'metadata' => json_encode(['capital' => 'Bandar Seri Begawan', 'region' => 'Southeast Asia', 'calling_code' => '+673']), 'display_order' => 96, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KH', 'name' => 'Cambodia', 'description' => 'Kingdom of Cambodia', 'type' => 'country', 'value' => '+855', 'metadata' => json_encode(['capital' => 'Phnom Penh', 'region' => 'Southeast Asia', 'calling_code' => '+855']), 'display_order' => 97, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CN', 'name' => 'China', 'description' => 'People\'s Republic of China', 'type' => 'country', 'value' => '+86', 'metadata' => json_encode(['capital' => 'Beijing', 'region' => 'East Asia', 'calling_code' => '+86']), 'display_order' => 98, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CY', 'name' => 'Cyprus', 'description' => 'Republic of Cyprus', 'type' => 'country', 'value' => '+357', 'metadata' => json_encode(['capital' => 'Nicosia', 'region' => 'Western Asia', 'calling_code' => '+357']), 'display_order' => 99, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GE', 'name' => 'Georgia', 'description' => 'Georgia', 'type' => 'country', 'value' => '+995', 'metadata' => json_encode(['capital' => 'Tbilisi', 'region' => 'Western Asia', 'calling_code' => '+995']), 'display_order' => 100, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IN', 'name' => 'India', 'description' => 'Republic of India', 'type' => 'country', 'value' => '+91', 'metadata' => json_encode(['capital' => 'New Delhi', 'region' => 'South Asia', 'calling_code' => '+91']), 'display_order' => 101, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ID', 'name' => 'Indonesia', 'description' => 'Republic of Indonesia', 'type' => 'country', 'value' => '+62', 'metadata' => json_encode(['capital' => 'Jakarta', 'region' => 'Southeast Asia', 'calling_code' => '+62']), 'display_order' => 102, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IR', 'name' => 'Iran', 'description' => 'Islamic Republic of Iran', 'type' => 'country', 'value' => '+98', 'metadata' => json_encode(['capital' => 'Tehran', 'region' => 'Western Asia', 'calling_code' => '+98']), 'display_order' => 103, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IQ', 'name' => 'Iraq', 'description' => 'Republic of Iraq', 'type' => 'country', 'value' => '+964', 'metadata' => json_encode(['capital' => 'Baghdad', 'region' => 'Middle East', 'calling_code' => '+964']), 'display_order' => 104, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IL', 'name' => 'Israel', 'description' => 'State of Israel', 'type' => 'country', 'value' => '+972', 'metadata' => json_encode(['capital' => 'Jerusalem', 'region' => 'Middle East', 'calling_code' => '+972']), 'display_order' => 105, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'JP', 'name' => 'Japan', 'description' => 'Japan', 'type' => 'country', 'value' => '+81', 'metadata' => json_encode(['capital' => 'Tokyo', 'region' => 'East Asia', 'calling_code' => '+81']), 'display_order' => 106, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'JO', 'name' => 'Jordan', 'description' => 'Hashemite Kingdom of Jordan', 'type' => 'country', 'value' => '+962', 'metadata' => json_encode(['capital' => 'Amman', 'region' => 'Middle East', 'calling_code' => '+962']), 'display_order' => 107, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KZ', 'name' => 'Kazakhstan', 'description' => 'Republic of Kazakhstan', 'type' => 'country', 'value' => '+7', 'metadata' => json_encode(['capital' => 'Nur-Sultan', 'region' => 'Central Asia', 'calling_code' => '+7']), 'display_order' => 108, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KW', 'name' => 'Kuwait', 'description' => 'State of Kuwait', 'type' => 'country', 'value' => '+965', 'metadata' => json_encode(['capital' => 'Kuwait City', 'region' => 'Middle East', 'calling_code' => '+965']), 'display_order' => 109, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KG', 'name' => 'Kyrgyzstan', 'description' => 'Kyrgyz Republic', 'type' => 'country', 'value' => '+996', 'metadata' => json_encode(['capital' => 'Bishkek', 'region' => 'Central Asia', 'calling_code' => '+996']), 'display_order' => 110, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LA', 'name' => 'Laos', 'description' => 'Lao People\'s Democratic Republic', 'type' => 'country', 'value' => '+856', 'metadata' => json_encode(['capital' => 'Vientiane', 'region' => 'Southeast Asia', 'calling_code' => '+856']), 'display_order' => 111, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LB', 'name' => 'Lebanon', 'description' => 'Lebanese Republic', 'type' => 'country', 'value' => '+961', 'metadata' => json_encode(['capital' => 'Beirut', 'region' => 'Middle East', 'calling_code' => '+961']), 'display_order' => 112, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MY', 'name' => 'Malaysia', 'description' => 'Malaysia', 'type' => 'country', 'value' => '+60', 'metadata' => json_encode(['capital' => 'Kuala Lumpur', 'region' => 'Southeast Asia', 'calling_code' => '+60']), 'display_order' => 113, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MV', 'name' => 'Maldives', 'description' => 'Republic of Maldives', 'type' => 'country', 'value' => '+960', 'metadata' => json_encode(['capital' => 'Malé', 'region' => 'South Asia', 'calling_code' => '+960']), 'display_order' => 114, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MN', 'name' => 'Mongolia', 'description' => 'Mongolia', 'type' => 'country', 'value' => '+976', 'metadata' => json_encode(['capital' => 'Ulaanbaatar', 'region' => 'East Asia', 'calling_code' => '+976']), 'display_order' => 115, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MM', 'name' => 'Myanmar', 'description' => 'Republic of the Union of Myanmar', 'type' => 'country', 'value' => '+95', 'metadata' => json_encode(['capital' => 'Naypyidaw', 'region' => 'Southeast Asia', 'calling_code' => '+95']), 'display_order' => 116, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NP', 'name' => 'Nepal', 'description' => 'Federal Democratic Republic of Nepal', 'type' => 'country', 'value' => '+977', 'metadata' => json_encode(['capital' => 'Kathmandu', 'region' => 'South Asia', 'calling_code' => '+977']), 'display_order' => 117, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KP', 'name' => 'North Korea', 'description' => 'Democratic People\'s Republic of Korea', 'type' => 'country', 'value' => '+850', 'metadata' => json_encode(['capital' => 'Pyongyang', 'region' => 'East Asia', 'calling_code' => '+850']), 'display_order' => 118, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'OM', 'name' => 'Oman', 'description' => 'Sultanate of Oman', 'type' => 'country', 'value' => '+968', 'metadata' => json_encode(['capital' => 'Muscat', 'region' => 'Middle East', 'calling_code' => '+968']), 'display_order' => 119, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PK', 'name' => 'Pakistan', 'description' => 'Islamic Republic of Pakistan', 'type' => 'country', 'value' => '+92', 'metadata' => json_encode(['capital' => 'Islamabad', 'region' => 'South Asia', 'calling_code' => '+92']), 'display_order' => 120, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PS', 'name' => 'Palestine', 'description' => 'State of Palestine', 'type' => 'country', 'value' => '+970', 'metadata' => json_encode(['capital' => 'Ramallah', 'region' => 'Middle East', 'calling_code' => '+970']), 'display_order' => 121, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PH', 'name' => 'Philippines', 'description' => 'Republic of the Philippines', 'type' => 'country', 'value' => '+63', 'metadata' => json_encode(['capital' => 'Manila', 'region' => 'Southeast Asia', 'calling_code' => '+63']), 'display_order' => 122, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'QA', 'name' => 'Qatar', 'description' => 'State of Qatar', 'type' => 'country', 'value' => '+974', 'metadata' => json_encode(['capital' => 'Doha', 'region' => 'Middle East', 'calling_code' => '+974']), 'display_order' => 123, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SA', 'name' => 'Saudi Arabia', 'description' => 'Kingdom of Saudi Arabia', 'type' => 'country', 'value' => '+966', 'metadata' => json_encode(['capital' => 'Riyadh', 'region' => 'Middle East', 'calling_code' => '+966']), 'display_order' => 124, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SG', 'name' => 'Singapore', 'description' => 'Republic of Singapore', 'type' => 'country', 'value' => '+65', 'metadata' => json_encode(['capital' => 'Singapore', 'region' => 'Southeast Asia', 'calling_code' => '+65']), 'display_order' => 125, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KR', 'name' => 'South Korea', 'description' => 'Republic of Korea', 'type' => 'country', 'value' => '+82', 'metadata' => json_encode(['capital' => 'Seoul', 'region' => 'East Asia', 'calling_code' => '+82']), 'display_order' => 126, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LK', 'name' => 'Sri Lanka', 'description' => 'Democratic Socialist Republic of Sri Lanka', 'type' => 'country', 'value' => '+94', 'metadata' => json_encode(['capital' => 'Sri Jayawardenepura Kotte', 'region' => 'South Asia', 'calling_code' => '+94']), 'display_order' => 127, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SY', 'name' => 'Syria', 'description' => 'Syrian Arab Republic', 'type' => 'country', 'value' => '+963', 'metadata' => json_encode(['capital' => 'Damascus', 'region' => 'Middle East', 'calling_code' => '+963']), 'display_order' => 128, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TW', 'name' => 'Taiwan', 'description' => 'Republic of China (Taiwan)', 'type' => 'country', 'value' => '+886', 'metadata' => json_encode(['capital' => 'Taipei', 'region' => 'East Asia', 'calling_code' => '+886']), 'display_order' => 129, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TJ', 'name' => 'Tajikistan', 'description' => 'Republic of Tajikistan', 'type' => 'country', 'value' => '+992', 'metadata' => json_encode(['capital' => 'Dushanbe', 'region' => 'Central Asia', 'calling_code' => '+992']), 'display_order' => 130, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TH', 'name' => 'Thailand', 'description' => 'Kingdom of Thailand', 'type' => 'country', 'value' => '+66', 'metadata' => json_encode(['capital' => 'Bangkok', 'region' => 'Southeast Asia', 'calling_code' => '+66']), 'display_order' => 131, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TL', 'name' => 'Timor-Leste', 'description' => 'Democratic Republic of Timor-Leste', 'type' => 'country', 'value' => '+670', 'metadata' => json_encode(['capital' => 'Dili', 'region' => 'Southeast Asia', 'calling_code' => '+670']), 'display_order' => 132, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TR', 'name' => 'Turkey', 'description' => 'Republic of Turkey', 'type' => 'country', 'value' => '+90', 'metadata' => json_encode(['capital' => 'Ankara', 'region' => 'Western Asia', 'calling_code' => '+90']), 'display_order' => 133, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TM', 'name' => 'Turkmenistan', 'description' => 'Turkmenistan', 'type' => 'country', 'value' => '+993', 'metadata' => json_encode(['capital' => 'Ashgabat', 'region' => 'Central Asia', 'calling_code' => '+993']), 'display_order' => 134, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AE', 'name' => 'United Arab Emirates', 'description' => 'United Arab Emirates', 'type' => 'country', 'value' => '+971', 'metadata' => json_encode(['capital' => 'Abu Dhabi', 'region' => 'Middle East', 'calling_code' => '+971']), 'display_order' => 135, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'UZ', 'name' => 'Uzbekistan', 'description' => 'Republic of Uzbekistan', 'type' => 'country', 'value' => '+998', 'metadata' => json_encode(['capital' => 'Tashkent', 'region' => 'Central Asia', 'calling_code' => '+998']), 'display_order' => 136, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'VN', 'name' => 'Vietnam', 'description' => 'Socialist Republic of Vietnam', 'type' => 'country', 'value' => '+84', 'metadata' => json_encode(['capital' => 'Hanoi', 'region' => 'Southeast Asia', 'calling_code' => '+84']), 'display_order' => 137, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'YE', 'name' => 'Yemen', 'description' => 'Republic of Yemen', 'type' => 'country', 'value' => '+967', 'metadata' => json_encode(['capital' => 'Sana\'a', 'region' => 'Middle East', 'calling_code' => '+967']), 'display_order' => 138, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Europe
            ['category_id' => $countryCategory->id, 'code' => 'AL', 'name' => 'Albania', 'description' => 'Republic of Albania', 'type' => 'country', 'value' => '+355', 'metadata' => json_encode(['capital' => 'Tirana', 'region' => 'Southern Europe', 'calling_code' => '+355']), 'display_order' => 139, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AD', 'name' => 'Andorra', 'description' => 'Principality of Andorra', 'type' => 'country', 'value' => '+376', 'metadata' => json_encode(['capital' => 'Andorra la Vella', 'region' => 'Southern Europe', 'calling_code' => '+376']), 'display_order' => 140, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'AT', 'name' => 'Austria', 'description' => 'Republic of Austria', 'type' => 'country', 'value' => '+43', 'metadata' => json_encode(['capital' => 'Vienna', 'region' => 'Western Europe', 'calling_code' => '+43']), 'display_order' => 141, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BY', 'name' => 'Belarus', 'description' => 'Republic of Belarus', 'type' => 'country', 'value' => '+375', 'metadata' => json_encode(['capital' => 'Minsk', 'region' => 'Eastern Europe', 'calling_code' => '+375']), 'display_order' => 142, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BE', 'name' => 'Belgium', 'description' => 'Kingdom of Belgium', 'type' => 'country', 'value' => '+32', 'metadata' => json_encode(['capital' => 'Brussels', 'region' => 'Western Europe', 'calling_code' => '+32']), 'display_order' => 143, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'description' => 'Bosnia and Herzegovina', 'type' => 'country', 'value' => '+387', 'metadata' => json_encode(['capital' => 'Sarajevo', 'region' => 'Southern Europe', 'calling_code' => '+387']), 'display_order' => 144, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'BG', 'name' => 'Bulgaria', 'description' => 'Republic of Bulgaria', 'type' => 'country', 'value' => '+359', 'metadata' => json_encode(['capital' => 'Sofia', 'region' => 'Eastern Europe', 'calling_code' => '+359']), 'display_order' => 145, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'HR', 'name' => 'Croatia', 'description' => 'Republic of Croatia', 'type' => 'country', 'value' => '+385', 'metadata' => json_encode(['capital' => 'Zagreb', 'region' => 'Southern Europe', 'calling_code' => '+385']), 'display_order' => 146, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CZ', 'name' => 'Czech Republic', 'description' => 'Czech Republic', 'type' => 'country', 'value' => '+420', 'metadata' => json_encode(['capital' => 'Prague', 'region' => 'Eastern Europe', 'calling_code' => '+420']), 'display_order' => 147, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'DK', 'name' => 'Denmark', 'description' => 'Kingdom of Denmark', 'type' => 'country', 'value' => '+45', 'metadata' => json_encode(['capital' => 'Copenhagen', 'region' => 'Northern Europe', 'calling_code' => '+45']), 'display_order' => 148, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'EE', 'name' => 'Estonia', 'description' => 'Republic of Estonia', 'type' => 'country', 'value' => '+372', 'metadata' => json_encode(['capital' => 'Tallinn', 'region' => 'Northern Europe', 'calling_code' => '+372']), 'display_order' => 149, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'FI', 'name' => 'Finland', 'description' => 'Republic of Finland', 'type' => 'country', 'value' => '+358', 'metadata' => json_encode(['capital' => 'Helsinki', 'region' => 'Northern Europe', 'calling_code' => '+358']), 'display_order' => 150, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'FR', 'name' => 'France', 'description' => 'French Republic', 'type' => 'country', 'value' => '+33', 'metadata' => json_encode(['capital' => 'Paris', 'region' => 'Western Europe', 'calling_code' => '+33']), 'display_order' => 151, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'DE', 'name' => 'Germany', 'description' => 'Federal Republic of Germany', 'type' => 'country', 'value' => '+49', 'metadata' => json_encode(['capital' => 'Berlin', 'region' => 'Western Europe', 'calling_code' => '+49']), 'display_order' => 152, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GR', 'name' => 'Greece', 'description' => 'Hellenic Republic', 'type' => 'country', 'value' => '+30', 'metadata' => json_encode(['capital' => 'Athens', 'region' => 'Southern Europe', 'calling_code' => '+30']), 'display_order' => 153, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'HU', 'name' => 'Hungary', 'description' => 'Hungary', 'type' => 'country', 'value' => '+36', 'metadata' => json_encode(['capital' => 'Budapest', 'region' => 'Eastern Europe', 'calling_code' => '+36']), 'display_order' => 154, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IS', 'name' => 'Iceland', 'description' => 'Iceland', 'type' => 'country', 'value' => '+354', 'metadata' => json_encode(['capital' => 'Reykjavik', 'region' => 'Northern Europe', 'calling_code' => '+354']), 'display_order' => 155, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IE', 'name' => 'Ireland', 'description' => 'Republic of Ireland', 'type' => 'country', 'value' => '+353', 'metadata' => json_encode(['capital' => 'Dublin', 'region' => 'Northern Europe', 'calling_code' => '+353']), 'display_order' => 156, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'IT', 'name' => 'Italy', 'description' => 'Italian Republic', 'type' => 'country', 'value' => '+39', 'metadata' => json_encode(['capital' => 'Rome', 'region' => 'Southern Europe', 'calling_code' => '+39']), 'display_order' => 157, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'XK', 'name' => 'Kosovo', 'description' => 'Republic of Kosovo', 'type' => 'country', 'value' => '+383', 'metadata' => json_encode(['capital' => 'Pristina', 'region' => 'Southern Europe', 'calling_code' => '+383']), 'display_order' => 158, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LV', 'name' => 'Latvia', 'description' => 'Republic of Latvia', 'type' => 'country', 'value' => '+371', 'metadata' => json_encode(['capital' => 'Riga', 'region' => 'Northern Europe', 'calling_code' => '+371']), 'display_order' => 159, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LI', 'name' => 'Liechtenstein', 'description' => 'Principality of Liechtenstein', 'type' => 'country', 'value' => '+423', 'metadata' => json_encode(['capital' => 'Vaduz', 'region' => 'Western Europe', 'calling_code' => '+423']), 'display_order' => 160, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LT', 'name' => 'Lithuania', 'description' => 'Republic of Lithuania', 'type' => 'country', 'value' => '+370', 'metadata' => json_encode(['capital' => 'Vilnius', 'region' => 'Northern Europe', 'calling_code' => '+370']), 'display_order' => 161, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'LU', 'name' => 'Luxembourg', 'description' => 'Grand Duchy of Luxembourg', 'type' => 'country', 'value' => '+352', 'metadata' => json_encode(['capital' => 'Luxembourg', 'region' => 'Western Europe', 'calling_code' => '+352']), 'display_order' => 162, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MT', 'name' => 'Malta', 'description' => 'Republic of Malta', 'type' => 'country', 'value' => '+356', 'metadata' => json_encode(['capital' => 'Valletta', 'region' => 'Southern Europe', 'calling_code' => '+356']), 'display_order' => 163, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MD', 'name' => 'Moldova', 'description' => 'Republic of Moldova', 'type' => 'country', 'value' => '+373', 'metadata' => json_encode(['capital' => 'Chișinău', 'region' => 'Eastern Europe', 'calling_code' => '+373']), 'display_order' => 164, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MC', 'name' => 'Monaco', 'description' => 'Principality of Monaco', 'type' => 'country', 'value' => '+377', 'metadata' => json_encode(['capital' => 'Monaco', 'region' => 'Western Europe', 'calling_code' => '+377']), 'display_order' => 165, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ME', 'name' => 'Montenegro', 'description' => 'Montenegro', 'type' => 'country', 'value' => '+382', 'metadata' => json_encode(['capital' => 'Podgorica', 'region' => 'Southern Europe', 'calling_code' => '+382']), 'display_order' => 166, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NL', 'name' => 'Netherlands', 'description' => 'Kingdom of the Netherlands', 'type' => 'country', 'value' => '+31', 'metadata' => json_encode(['capital' => 'Amsterdam', 'region' => 'Western Europe', 'calling_code' => '+31']), 'display_order' => 167, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MK', 'name' => 'North Macedonia', 'description' => 'Republic of North Macedonia', 'type' => 'country', 'value' => '+389', 'metadata' => json_encode(['capital' => 'Skopje', 'region' => 'Southern Europe', 'calling_code' => '+389']), 'display_order' => 168, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NO', 'name' => 'Norway', 'description' => 'Kingdom of Norway', 'type' => 'country', 'value' => '+47', 'metadata' => json_encode(['capital' => 'Oslo', 'region' => 'Northern Europe', 'calling_code' => '+47']), 'display_order' => 169, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PL', 'name' => 'Poland', 'description' => 'Republic of Poland', 'type' => 'country', 'value' => '+48', 'metadata' => json_encode(['capital' => 'Warsaw', 'region' => 'Eastern Europe', 'calling_code' => '+48']), 'display_order' => 170, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PT', 'name' => 'Portugal', 'description' => 'Portuguese Republic', 'type' => 'country', 'value' => '+351', 'metadata' => json_encode(['capital' => 'Lisbon', 'region' => 'Southern Europe', 'calling_code' => '+351']), 'display_order' => 171, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'RO', 'name' => 'Romania', 'description' => 'Romania', 'type' => 'country', 'value' => '+40', 'metadata' => json_encode(['capital' => 'Bucharest', 'region' => 'Eastern Europe', 'calling_code' => '+40']), 'display_order' => 172, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'RU', 'name' => 'Russia', 'description' => 'Russian Federation', 'type' => 'country', 'value' => '+7', 'metadata' => json_encode(['capital' => 'Moscow', 'region' => 'Eastern Europe', 'calling_code' => '+7']), 'display_order' => 173, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SM', 'name' => 'San Marino', 'description' => 'Republic of San Marino', 'type' => 'country', 'value' => '+378', 'metadata' => json_encode(['capital' => 'San Marino', 'region' => 'Southern Europe', 'calling_code' => '+378']), 'display_order' => 174, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'RS', 'name' => 'Serbia', 'description' => 'Republic of Serbia', 'type' => 'country', 'value' => '+381', 'metadata' => json_encode(['capital' => 'Belgrade', 'region' => 'Southern Europe', 'calling_code' => '+381']), 'display_order' => 175, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SK', 'name' => 'Slovakia', 'description' => 'Slovak Republic', 'type' => 'country', 'value' => '+421', 'metadata' => json_encode(['capital' => 'Bratislava', 'region' => 'Eastern Europe', 'calling_code' => '+421']), 'display_order' => 176, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SI', 'name' => 'Slovenia', 'description' => 'Republic of Slovenia', 'type' => 'country', 'value' => '+386', 'metadata' => json_encode(['capital' => 'Ljubljana', 'region' => 'Southern Europe', 'calling_code' => '+386']), 'display_order' => 177, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'ES', 'name' => 'Spain', 'description' => 'Kingdom of Spain', 'type' => 'country', 'value' => '+34', 'metadata' => json_encode(['capital' => 'Madrid', 'region' => 'Southern Europe', 'calling_code' => '+34']), 'display_order' => 178, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SE', 'name' => 'Sweden', 'description' => 'Kingdom of Sweden', 'type' => 'country', 'value' => '+46', 'metadata' => json_encode(['capital' => 'Stockholm', 'region' => 'Northern Europe', 'calling_code' => '+46']), 'display_order' => 179, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'CH', 'name' => 'Switzerland', 'description' => 'Swiss Confederation', 'type' => 'country', 'value' => '+41', 'metadata' => json_encode(['capital' => 'Bern', 'region' => 'Western Europe', 'calling_code' => '+41']), 'display_order' => 180, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'UA', 'name' => 'Ukraine', 'description' => 'Ukraine', 'type' => 'country', 'value' => '+380', 'metadata' => json_encode(['capital' => 'Kyiv', 'region' => 'Eastern Europe', 'calling_code' => '+380']), 'display_order' => 181, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'GB', 'name' => 'United Kingdom', 'description' => 'United Kingdom of Great Britain and Northern Ireland', 'type' => 'country', 'value' => '+44', 'metadata' => json_encode(['capital' => 'London', 'region' => 'Northern Europe', 'calling_code' => '+44']), 'display_order' => 182, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'VA', 'name' => 'Vatican City', 'description' => 'Vatican City State', 'type' => 'country', 'value' => '+379', 'metadata' => json_encode(['capital' => 'Vatican City', 'region' => 'Southern Europe', 'calling_code' => '+379']), 'display_order' => 183, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Oceania
            ['category_id' => $countryCategory->id, 'code' => 'AU', 'name' => 'Australia', 'description' => 'Commonwealth of Australia', 'type' => 'country', 'value' => '+61', 'metadata' => json_encode(['capital' => 'Canberra', 'region' => 'Oceania', 'calling_code' => '+61']), 'display_order' => 184, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'FJ', 'name' => 'Fiji', 'description' => 'Republic of Fiji', 'type' => 'country', 'value' => '+679', 'metadata' => json_encode(['capital' => 'Suva', 'region' => 'Oceania', 'calling_code' => '+679']), 'display_order' => 185, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'KI', 'name' => 'Kiribati', 'description' => 'Republic of Kiribati', 'type' => 'country', 'value' => '+686', 'metadata' => json_encode(['capital' => 'Tarawa', 'region' => 'Oceania', 'calling_code' => '+686']), 'display_order' => 186, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'MH', 'name' => 'Marshall Islands', 'description' => 'Republic of the Marshall Islands', 'type' => 'country', 'value' => '+692', 'metadata' => json_encode(['capital' => 'Majuro', 'region' => 'Oceania', 'calling_code' => '+692']), 'display_order' => 187, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'FM', 'name' => 'Micronesia', 'description' => 'Federated States of Micronesia', 'type' => 'country', 'value' => '+691', 'metadata' => json_encode(['capital' => 'Palikir', 'region' => 'Oceania', 'calling_code' => '+691']), 'display_order' => 188, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NR', 'name' => 'Nauru', 'description' => 'Republic of Nauru', 'type' => 'country', 'value' => '+674', 'metadata' => json_encode(['capital' => 'Yaren', 'region' => 'Oceania', 'calling_code' => '+674']), 'display_order' => 189, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'NZ', 'name' => 'New Zealand', 'description' => 'New Zealand', 'type' => 'country', 'value' => '+64', 'metadata' => json_encode(['capital' => 'Wellington', 'region' => 'Oceania', 'calling_code' => '+64']), 'display_order' => 190, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PW', 'name' => 'Palau', 'description' => 'Republic of Palau', 'type' => 'country', 'value' => '+680', 'metadata' => json_encode(['capital' => 'Ngerulmud', 'region' => 'Oceania', 'calling_code' => '+680']), 'display_order' => 191, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'PG', 'name' => 'Papua New Guinea', 'description' => 'Independent State of Papua New Guinea', 'type' => 'country', 'value' => '+675', 'metadata' => json_encode(['capital' => 'Port Moresby', 'region' => 'Oceania', 'calling_code' => '+675']), 'display_order' => 192, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'WS', 'name' => 'Samoa', 'description' => 'Independent State of Samoa', 'type' => 'country', 'value' => '+685', 'metadata' => json_encode(['capital' => 'Apia', 'region' => 'Oceania', 'calling_code' => '+685']), 'display_order' => 193, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'SB', 'name' => 'Solomon Islands', 'description' => 'Solomon Islands', 'type' => 'country', 'value' => '+677', 'metadata' => json_encode(['capital' => 'Honiara', 'region' => 'Oceania', 'calling_code' => '+677']), 'display_order' => 194, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TO', 'name' => 'Tonga', 'description' => 'Kingdom of Tonga', 'type' => 'country', 'value' => '+676', 'metadata' => json_encode(['capital' => 'Nuku\'alofa', 'region' => 'Oceania', 'calling_code' => '+676']), 'display_order' => 195, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'TV', 'name' => 'Tuvalu', 'description' => 'Tuvalu', 'type' => 'country', 'value' => '+688', 'metadata' => json_encode(['capital' => 'Funafuti', 'region' => 'Oceania', 'calling_code' => '+688']), 'display_order' => 196, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $countryCategory->id, 'code' => 'VU', 'name' => 'Vanuatu', 'description' => 'Republic of Vanuatu', 'type' => 'country', 'value' => '+678', 'metadata' => json_encode(['capital' => 'Port Vila', 'region' => 'Oceania', 'calling_code' => '+678']), 'display_order' => 197, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($countries as $country) {
            DB::table('master_data')->updateOrInsert(
                ['code' => $country['code']],
                $country
            );
        }

        // Seed Currencies
        $currencies = [
            ['category_id' => $currencyCategory->id, 'code' => 'UGX', 'name' => 'Uganda Shilling', 'description' => 'Ugandan Shilling', 'type' => 'currency', 'unit' => 'UGX', 'metadata' => json_encode(['symbol' => 'USh', 'decimal_places' => 0, 'country' => 'Uganda']), 'display_order' => 1, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'USD', 'name' => 'US Dollar', 'description' => 'United States Dollar', 'type' => 'currency', 'unit' => 'USD', 'metadata' => json_encode(['symbol' => '$', 'decimal_places' => 2, 'country' => 'United States']), 'display_order' => 2, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'EUR', 'name' => 'Euro', 'description' => 'European Euro', 'type' => 'currency', 'unit' => 'EUR', 'metadata' => json_encode(['symbol' => '€', 'decimal_places' => 2, 'country' => 'European Union']), 'display_order' => 3, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'GBP', 'name' => 'British Pound', 'description' => 'British Pound Sterling', 'type' => 'currency', 'unit' => 'GBP', 'metadata' => json_encode(['symbol' => '£', 'decimal_places' => 2, 'country' => 'United Kingdom']), 'display_order' => 4, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'KES', 'name' => 'Kenya Shilling', 'description' => 'Kenyan Shilling', 'type' => 'currency', 'unit' => 'KES', 'metadata' => json_encode(['symbol' => 'KSh', 'decimal_places' => 2, 'country' => 'Kenya']), 'display_order' => 5, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'TZS', 'name' => 'Tanzania Shilling', 'description' => 'Tanzanian Shilling', 'type' => 'currency', 'unit' => 'TZS', 'metadata' => json_encode(['symbol' => 'TSh', 'decimal_places' => 0, 'country' => 'Tanzania']), 'display_order' => 6, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'RWF', 'name' => 'Rwanda Franc', 'description' => 'Rwandan Franc', 'type' => 'currency', 'unit' => 'RWF', 'metadata' => json_encode(['symbol' => 'FRw', 'decimal_places' => 0, 'country' => 'Rwanda']), 'display_order' => 7, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'ZAR', 'name' => 'South African Rand', 'description' => 'South African Rand', 'type' => 'currency', 'unit' => 'ZAR', 'metadata' => json_encode(['symbol' => 'R', 'decimal_places' => 2, 'country' => 'South Africa']), 'display_order' => 8, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'AED', 'name' => 'UAE Dirham', 'description' => 'United Arab Emirates Dirham', 'type' => 'currency', 'unit' => 'AED', 'metadata' => json_encode(['symbol' => 'د.إ', 'decimal_places' => 2, 'country' => 'UAE']), 'display_order' => 9, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $currencyCategory->id, 'code' => 'CNY', 'name' => 'Chinese Yuan', 'description' => 'Chinese Yuan Renminbi', 'type' => 'currency', 'unit' => 'CNY', 'metadata' => json_encode(['symbol' => '¥', 'decimal_places' => 2, 'country' => 'China']), 'display_order' => 10, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($currencies as $currency) {
            DB::table('master_data')->updateOrInsert(
                ['code' => $currency['code']],
                $currency
            );
        }

        // Seed Units of Measure
        $unitsOfMeasure = [
            // Length
            ['category_id' => $uomCategory->id, 'code' => 'MM', 'name' => 'Millimeter', 'description' => 'Millimeter (mm)', 'type' => 'length', 'unit' => 'mm', 'display_order' => 1, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'CM', 'name' => 'Centimeter', 'description' => 'Centimeter (cm)', 'type' => 'length', 'unit' => 'cm', 'display_order' => 2, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'M', 'name' => 'Meter', 'description' => 'Meter (m)', 'type' => 'length', 'unit' => 'm', 'display_order' => 3, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'KM', 'name' => 'Kilometer', 'description' => 'Kilometer (km)', 'type' => 'length', 'unit' => 'km', 'display_order' => 4, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'IN', 'name' => 'Inch', 'description' => 'Inch (in)', 'type' => 'length', 'unit' => 'in', 'display_order' => 5, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'FT', 'name' => 'Feet', 'description' => 'Feet (ft)', 'type' => 'length', 'unit' => 'ft', 'display_order' => 6, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Weight
            ['category_id' => $uomCategory->id, 'code' => 'MG', 'name' => 'Milligram', 'description' => 'Milligram (mg)', 'type' => 'weight', 'unit' => 'mg', 'display_order' => 7, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'G', 'name' => 'Gram', 'description' => 'Gram (g)', 'type' => 'weight', 'unit' => 'g', 'display_order' => 8, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'KG', 'name' => 'Kilogram', 'description' => 'Kilogram (kg)', 'type' => 'weight', 'unit' => 'kg', 'display_order' => 9, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'TON', 'name' => 'Metric Ton', 'description' => 'Metric Ton (t)', 'type' => 'weight', 'unit' => 't', 'display_order' => 10, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'LB', 'name' => 'Pound', 'description' => 'Pound (lb)', 'type' => 'weight', 'unit' => 'lb', 'display_order' => 11, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Volume
            ['category_id' => $uomCategory->id, 'code' => 'ML', 'name' => 'Milliliter', 'description' => 'Milliliter (ml)', 'type' => 'volume', 'unit' => 'ml', 'display_order' => 12, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'L', 'name' => 'Liter', 'description' => 'Liter (l)', 'type' => 'volume', 'unit' => 'l', 'display_order' => 13, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'GAL', 'name' => 'Gallon', 'description' => 'Gallon (gal)', 'type' => 'volume', 'unit' => 'gal', 'display_order' => 14, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Quantity
            ['category_id' => $uomCategory->id, 'code' => 'PCS', 'name' => 'Pieces', 'description' => 'Pieces (pcs)', 'type' => 'quantity', 'unit' => 'pcs', 'display_order' => 15, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'EA', 'name' => 'Each', 'description' => 'Each (ea)', 'type' => 'quantity', 'unit' => 'ea', 'display_order' => 16, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'SET', 'name' => 'Set', 'description' => 'Set', 'type' => 'quantity', 'unit' => 'set', 'display_order' => 17, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'BOX', 'name' => 'Box', 'description' => 'Box', 'type' => 'quantity', 'unit' => 'box', 'display_order' => 18, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'PACK', 'name' => 'Pack', 'description' => 'Pack', 'type' => 'quantity', 'unit' => 'pack', 'display_order' => 19, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'CARTON', 'name' => 'Carton', 'description' => 'Carton', 'type' => 'quantity', 'unit' => 'carton', 'display_order' => 20, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'DOZEN', 'name' => 'Dozen', 'description' => 'Dozen (12 units)', 'type' => 'quantity', 'unit' => 'dozen', 'display_order' => 21, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Area
            ['category_id' => $uomCategory->id, 'code' => 'SQM', 'name' => 'Square Meter', 'description' => 'Square Meter (m²)', 'type' => 'area', 'unit' => 'm²', 'display_order' => 22, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'SQFT', 'name' => 'Square Feet', 'description' => 'Square Feet (ft²)', 'type' => 'area', 'unit' => 'ft²', 'display_order' => 23, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            
            // Time
            ['category_id' => $uomCategory->id, 'code' => 'HR', 'name' => 'Hour', 'description' => 'Hour (hr)', 'type' => 'time', 'unit' => 'hr', 'display_order' => 24, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'DAY', 'name' => 'Day', 'description' => 'Day', 'type' => 'time', 'unit' => 'day', 'display_order' => 25, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'MONTH', 'name' => 'Month', 'description' => 'Month', 'type' => 'time', 'unit' => 'month', 'display_order' => 26, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['category_id' => $uomCategory->id, 'code' => 'YEAR', 'name' => 'Year', 'description' => 'Year', 'type' => 'time', 'unit' => 'year', 'display_order' => 27, 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($unitsOfMeasure as $uom) {
            DB::table('master_data')->updateOrInsert(
                ['code' => $uom['code']],
                $uom
            );
        }

        $this->command->info('Countries, Currencies, and Units of Measure seeded successfully!');
    }
}
